# Run Java Chains as pod
# k apply -f javachains.kubernetes.yaml
# k port-forward -n javachains pods/javachains 8011:8011
---
apiVersion: v1
kind: Namespace
metadata:
  name: javachains
---
apiVersion: v1
kind: Pod
metadata:
  name: javachains
  namespace: javachains
spec:
  containers:
    - image: javachains/javachains:latest
      name: javachains
      env:
        - name: CHAINS_AUTH
          value: "true"
        - name: CHAINS_PASS
          value: "admin"
      ports:
        # The payload generation function only requires port 8011, while other
        # ports are used for the exploit module.
        - containerPort: 8011
          name: chains-web
        - containerPort: 50389
          name: jndi-ldap
        - containerPort: 50388
          name: jndi-rmi
        - containerPort: 3308
          name: fake-mysql
        - containerPort: 13999
          name: jrmp-listener
        - containerPort: 50000
          name: http-server
        - containerPort: 11527
          name: tcp-server
