# k port-forward -n solr pods/solr 8983:8983
---
apiVersion: v1
kind: Namespace
metadata:
  name: solr
---
apiVersion: v1
kind: Pod
metadata:
  name: solr
  namespace: solr
spec:
  containers:
    - image: docker.io/vulhub/solr:8.11.0
      name: solr
      ports:
        - containerPort: 8983
        - containerPort: 5005
