---
apiVersion: v1
kind: Namespace
metadata:
  name: solr
---
apiVersion: v1
kind: Service
metadata:
  name: solr
  namespace: solr
spec:
  ports:
    - name: port1
      port: 8983
    - name: port2
      port: 5005
  selector:
    app: solr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
  namespace: solr
  labels:
    app: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
        - image: docker.io/vulhub/solr:8.11.0
          name: solr
          ports:
            - containerPort: 8983
            - containerPort: 5005
